### ISSUE TITLE
Not enough rory!

### ISSUE THREAD

**Issue by 7man7LMYT** [RorryMC/RoryMC#2]
Add more rory pics

**Comment by GenifeYouTube** [comment]
RRROORYY!!!

**Comment by BlAnKcOd3** [comment]
yes

**Comment by 7man7LMYT** [comment]
yes

**Comment by Heath123** [comment]
roottkrrororoy

**Comment by Heath123** [comment]
I was literally about to open an issue just like this

**Comment by 7man7LMYT** [comment]
> I was literally about to open an issue just like this

would of closed.it for.being a duplicate

**Comment by 7man7LMYT** [comment]
so we will fix and it's not a dupe
